backend:
  name: git-gateway
  branch: main

media_folder: static/assets
public_folder: /assets
editor:
  preview: false

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home Page
        file: content/pages/home.yml
        fields:
          - name: docTitle
            widget: string
          - name: section1
            widget: object
            fields:
              - name: title
                widget: string
              - name: description
                widget: string
              - name: image
                widget: image
          - name: section2
            widget: object
            fields:
              - name: title
                widget: string
              - name: description
                widget: string
              - name: image
                widget: image
          - name: section3
            widget: object
            fields:
              - name: title
                widget: string
              - name: description
                widget: string
              - name: image
                widget: image
          - name: section4
            widget: object
            fields:
              - name: title
                widget: string
              - name: description
                widget: string
              - name: image
                widget: image
