backend:
  name: git-gateway
  branch: main

media_folder: static/assets
public_folder: /assets
editor:
  preview: false

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home Page
        file: content/pages/home.yml
        fields:
          - name: docTitle
            widget: string
          - name: header
            widget: object
            fields:
              - label: Navigation
                name: navigation
                widget: object
                fields:
                  - label: Item 1
                    name: item1
                    widget: string
                  - label: Item 2
                    name: item2
                    widget: string
                  - label: Item 2
                    name: item2
                    widget: string
